fix: added a media queries for viewport until 320px
shelfio/insights-training-app pull request #46
Opened 2021-05-25 16:07 UTC by JaabaShooler

Table on the search queries page is adaptive for viewport until 320px
![image](https://user-images.githubusercontent.com/44289622/119531121-4d024e80-bd8c-11eb-951b-ddf133d29eba.png)

2021-05-25 16:08 UTC, hmelenok commented on src/components/Tools/Table/Table.scss
> +}
![Uploading Screenshot 2021-05-25 at 19.07.56.png…]()

2021-05-25 16:12 UTC, hmelenok commented on src/components/Tools/Table/Table.tsx
> +                  {query.firstColumn}
why just not create a map of `<label />` elements? what about the fifth element? what about sixth? What about n element?

2021-05-25 16:13 UTC, hmelenok requested changes
Fix table cols rendering, to not rely on property name

2021-05-25 16:48 UTC, JaabaShooler commented on src/components/Tools/Table/Table.tsx
> +                  {query.firstColumn}
Ok, its done i think

2021-05-25 16:53 UTC, JaabaShooler commented on src/components/Tools/Table/Table.scss
> +}
my bad

2021-05-26 08:05 UTC, hmelenok approved these changes

2021-05-26 08:48 UTC, merged