Feature/search queries report
shelfio/insights-training-app pull request #6
Opened 2021-05-14 14:49 UTC by JaabaShooler

2021-05-14 14:51 UTC, hmelenok commented on pages/SearchQueries.tsx
> +    document.body.addEventListener('click', onBoudyClick);
Typo: `onBoudyClick` -> `onBodyClick`

2021-05-14 14:51 UTC, hmelenok commented on src/components/Tools/Menu/Menu.scss
> +.menu {
Where is BEM?

2021-05-14 14:51 UTC, hmelenok commented on src/components/Tools/Menu/Menu.scss
> +  ul {
Please use classes

2021-05-14 14:52 UTC, hmelenok commented on src/components/Tools/Menu/Menu.tsx
> +    <></>
it can be null (as non existing element in React)

2021-05-14 14:53 UTC, hmelenok commented on src/components/Tools/Menu/Menu.tsx
> +              <img src="notNow" alt="exit " />
is it real image `src`?

2021-05-14 14:54 UTC, hmelenok commented on src/components/Tools/Menu/Menu.tsx
> +  menuItemArr: any[];
Please describe type of menu item. As it typed no reason to put `Arr` to name

2021-05-14 14:54 UTC, hmelenok commented on src/components/Tools/Menu/Menu.scss
> +        position: absolute;
Maybe there is better way?

2021-05-14 14:55 UTC, hmelenok requested changes
Please fix comments. And  please add screenshot with menu.

2021-05-14 14:59 UTC, pihorb reviewed
Better to use lower case for route names, because it's case sensitive. 
Now, open `searchqueries` will lead to error

2021-05-14 15:02 UTC, JaabaShooler commented on src/components/Tools/Menu/Menu.tsx
> +              <img src="notNow" alt="exit " />
no

2021-05-14 15:02 UTC, pihorb commented on pages/SearchQueries.tsx
> +    const onBoudyClick = (event: any) => {
please, avoid using `any`

2021-05-15 13:54 UTC, JaabaShooler commented on pages/SearchQueries.tsx
> +    const onBoudyClick = (event: any) => {
I need some help to choose correct type

2021-05-17 12:34 UTC, hmelenok commented on src/components/Tools/Menu/Menu.scss
> +.menu {
@JaabaShooler Please name it from capital letter

2021-05-17 12:34 UTC, hmelenok commented on src/components/Tools/Menu/Menu.scss
> +      img {
No direct `element` selectors

2021-05-17 12:35 UTC, hmelenok commented on src/components/Tools/Menu/Menu.tsx
> +                className="menu__nav__element"
why classes the same?

2021-05-17 16:10 UTC, hmelenok approved these changes

2021-05-17 16:15 UTC, slavik-chapelskyi commented on src/components/Tools/Menu/Menu.tsx
> +  menuItemArr: [{title: string; execute: () => void}];
```suggestion
  items: [{title: string; onClick: () => void}];
```

2021-05-17 16:28 UTC, merged